---
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.26
    hooks:
      - id: uv-lock # update lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        args: ["--fix"]
        files: ^(fine_memes|tests)/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: ^(fine_memes|tests)/
        types: [python]
