name: CI/CD

on:
  push:
    # branches:
    #   - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: psf/black@stable
        with:
          src: "./fine_memes"

  lint:
    name: Lint with ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: check --select E,W,F,B,I --ignore E501,E402
          src: "./fine_memes"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Python and uv 
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --group test

      - name: Run tests
        run: uv run pytest

  publish:
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: 
      - format
      - lint
      - test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          python-version: "3.12"
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
